# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9366cfff56d3658b0ad63d2270dad45155e2eeafc572f70731b4ccd5b1eb3d5c1fe6a0f746e69fa619a3013f17c5236faec1bd3b24eb3f3d897a23b7370e60be

test:
  secret_key_base: 5738449555d7b65d92b519fe09fbb87caaa84117b0fb57c0050f309a88dd477d656dbfe4e4cebb5172d297b336f8dc7a38d26393eb59acf099c00990fba3e33a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
